a:
	as dislpay_hex.s -o dislpay_hex.o
l:
	gcc -no-pie dislpay_hex.o -o dislpay_hex
clear:
	rm dislpay_hex.o dislpay_hex

a2:
	as printcharint.s -o printcharint.o
l2:
	gcc -no-pie printcharint.o -o printcharint
clear2:
	rm printcharint.o printcharint